export const REGISTER_REQUEST='REGISTER_REQUEST';
export const REGISTER_SUCCESSS='REGISTER_SUCCESSS';
export const REGISTER_FAILURE='REGISTER_FAILURE';

export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESSS='LOGIN_SUCCESSS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

export const GET_USER_REQUEST='GET_USER_REQUEST';
export const GET_USER__SUCCESSS='GET_USER_SUCCESSS';
export const GET_USER__FAILURE='GET_USER__FAILURE';


export const LOGOUT="LOGOUT";
